apiVersion: v2
name: tobs
description: A Helm chart for tobs, The Observability Stack for Kubernetes

type: application

version: 0.9.0
appVersion: 0.9.0

dependencies:
  - name: timescaledb-single
    condition: timescaledb-single.enabled
    version: 0.11.0
    repository: https://charts.timescale.com
  - name: promscale
    condition: promscale.enabled
    version: 0.10.0
    repository: https://charts.timescale.com
  - name: kube-prometheus-stack
    condition: kube-prometheus-stack.enabled
    version: 35.0.3
    repository: https://prometheus-community.github.io/helm-charts
  - name: opentelemetry-operator
    condition: opentelemetryOperator.enabled
    version: 0.6.7
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
