apiVersion: v2
name: tobs
description: A Helm chart for tobs, The Observability Stack for Kubernetes

type: application

version: 0.11.3
appVersion: 0.11.3
# TODO(paulfantom): Enable after kubernetes 1.22 reaches EOL (2022-10-28)
# kubeVersion: ">= 1.23.0"
dependencies:
  - name: timescaledb-single
    condition: timescaledb-single.enabled
    version: 0.14.0
    repository: https://charts.timescale.com
  - name: promscale
    condition: promscale.enabled
    version: 0.12.1
    repository: https://charts.timescale.com
  - name: kube-prometheus-stack
    condition: kube-prometheus-stack.enabled
    # With each major bump make sure prometheus-operator CRD version matches version specified in cli/pkg/upgrade/upgrade.go#KubePrometheusCRDVersion
    version: 37.3.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: opentelemetry-operator
    condition: opentelemetry-operator.enabled
    version: 0.9.4
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
