{{- $grafana := index .Values "kube-prometheus-stack" "grafana" -}}
{{ if $grafana.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-db
  namespace: {{ template "tobs.namespace" . }}
  labels:
    app: {{ template "tobs.fullname" . }}
    chart: {{ template "tobs.chart" . }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
{{- if (($grafana.timescale).database).enabled }}
data:
  {{- $isDBURI := (ne .Values.promscale.connection.uri "")}}
  {{- if $isDBURI}}
  GF_DATABASE_HOST: {{ include "tobs.dburi.host" . | b64enc }}
  GF_DATABASE_NAME: {{ include "tobs.dburi.dbname" . | b64enc }}
  GF_DATABASE_USER: {{ include "tobs.dburi.user" . | b64enc }}
  GF_DATABASE_PASSWORD: {{ include "tobs.dburi.password" . | b64enc }}
  GF_DATABASE_SSL_MODE: {{ include "tobs.dburi.sslmode" . | b64enc }}
  {{- else }}
  {{- $host := tpl $grafana.timescale.database.host $ -}}
  {{- $port := $grafana.timescale.database.port | int -}}
  {{- $fullhost := printf "%s:%d" $host $port }}
  GF_DATABASE_HOST: {{ $fullhost | b64enc }}
  GF_DATABASE_NAME: {{ $grafana.timescale.database.dbName | b64enc }}
  GF_DATABASE_USER: {{ $grafana.timescale.database.user | b64enc }}
  GF_DATABASE_PASSWORD: {{ $grafana.timescale.database.pass | b64enc }}
  GF_DATABASE_SSL_MODE: {{ $grafana.timescale.database.sslMode | b64enc }}
  {{- end }}
  GF_DATABASE_TYPE: {{ "postgres" | b64enc }}
{{- else }}
data:
  GF_DATABASE_TYPE: {{ "sqlite3" | b64enc }}
{{- end }}
{{- end }}
