{{- $grafana := index .Values "kube-prometheus-stack" "grafana" -}}
{{ if and $grafana.enabled $grafana.sidecar.datasources.enabled -}}
{{ if or $grafana.timescale.datasource.enabled $grafana.prometheus.datasource.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-datasources
  namespace: {{ template "tobs.namespace" . }}
  labels:
    tobs_datasource: "true"
    app: {{ template "tobs.fullname" . }}
    chart: {{ template "tobs.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  datasource.yaml: |-
    # config file version
    apiVersion: 1

    datasources:

{{- if $grafana.prometheus.datasource.enabled }}
      - name: Promscale-PromQL
        type: prometheus
        url: {{ tpl $grafana.prometheus.datasource.url . }}
        isDefault: true
        editable: true
        access: proxy
        # SHA256 of datasource name cut to 40 chars as in: `sha256sum <<< Promscale-PromQL | cut -c1-40`
        uid: dc08d25c8f267b054f12002f334e6d3d32a853e4
{{- end -}}

{{- if .Values.opentelemetryOperator.enabled }}
      - name: Promscale-Tracing
        type: jaeger
        url: {{ tpl $grafana.jaeger.promscaleTracesQueryEndPoint . }}
        editable: true
        access: proxy
        # SHA256 of datasource name cut to 40 chars as in: `sha256sum <<< Promscale-Tracing | cut -c1-40`
        uid: f78291126102e0f2e841734d1e90250257543042
{{- end -}}

{{ if $grafana.timescale.datasource.enabled -}}
{{- $isDBURI := (ne .Values.promscale.connection.uri "")}}
{{- $hostURL := "" -}}
{{ if $isDBURI -}}
  {{- $hostURL = include "tobs.dburi.host" . -}}
{{ else -}}
  {{- $host := tpl $grafana.timescale.datasource.host $ -}}
  {{- $port := $grafana.timescale.datasource.port | int -}}
  {{- $hostURL = printf "%s:%d" $host $port -}}
{{ end }}
      - name: Promscale-SQL
        url: {{ $hostURL }}
        type: postgres
        isDefault: {{ not $grafana.prometheus.datasource.enabled }}
        access: proxy
        # SHA256 of datasource name cut to 40 chars as in: `sha256sum <<< Promscale-SQL | cut -c1-40`
        uid: c4729dfb8ceeaa0372ef27403a3932695eee995d
        user: {{ ternary (include "tobs.dburi.user" . ) ($grafana.timescale.datasource.user) ($isDBURI) }}
        database: {{ ternary (include "tobs.dburi.dbname" . ) ($grafana.timescale.datasource.dbName) ($isDBURI) }}
        editable: true
        secureJsonData:
          password: {{ ternary (include "tobs.dburi.password" . ) ($grafana.timescale.datasource.pass) ($isDBURI) }}
        jsonData:
          sslmode: {{ ternary (include "tobs.dburi.sslmode" . ) ($grafana.timescale.datasource.sslMode) ($isDBURI) }}
          postgresVersion: 1000
          timescaledb: true
{{- end -}}

{{- end -}}
{{- end -}}