name: helm

on:
  push:
    paths:
    - chart/**
  pull_request:
    paths:
    - chart/**

jobs:
  template-test:
    name: Run helm template
    runs-on: ubuntu-latest
    strategy:
      matrix:
        timescaledb:
        - "true"
        - "false"
        promscale:
        - "promscale.connection.uri=postgres://tsdb:password@database.example.com:33253/tsdb?sslmode=require"
        - ""
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v2.0
      with:
        version: v3.7.1
    
    - name: Get helm dependencies
      working-directory: chart
      run: |
        helm dep up

    - name: Test templating
      working-directory: chart
      run: |
        helm template --generate-name . \
          --set 'timescaledb-single.enabled=${{ matrix.timescaledb }}' \
          --set '${{ matrix.promscale }}'