name: Daily scheduled Tests

on:
  push:
    branches: [force_test, release-*]
  schedule:
    - cron: "6 0 * * *"

defaults:
  run:
    working-directory: cli

env:
  golang-version: 1.17.8

jobs:
  golang:
    name: golang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go ${{ env.golang-version }}
        uses: actions/setup-go@v3.0.0
        with:
          go-version: ${{ env.golang-version }}

      - name: Unit-Tests
        run: |
          make unit-tests

      - name: Dependency-Tests
        run: |
          go test -v ./tests/dependency-tests

  all-tests:
    name: All
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kube-version:
          - "1.21"
          - "1.22"
          - "1.23"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go ${{ env.golang-version }}
        uses: actions/setup-go@v3.0.0
        with:
          go-version: ${{ env.golang-version }}

      - name: Build
        working-directory: ${{env.working-directory}}
        run: |
          make build

      - name: All-Tests
        working-directory: ${{env.working-directory}}
        env:
          KUBE_VERSION: ${{ matrix.kube-version }}
        run: |
          make start-kind helm-tests e2e-tests external-db-tests ha-tests install-tests delete-kind KUBE_VERSION=$KUBE_VERSION
